version: '3'
services:
    nginx:
        image: nginx
        ports:
        - "80:80"
        volumes:
        - './nginx/default:/etc/nginx/conf.d/default.conf'
        - '../src:/code'

    php7:
        image: php:7.3-fpm
        expose:
        - 9000
        volumes:
            - '../src:/code'
            - './php/php.ini:/usr/local/etc/php/conf.d/php_extra.ini'
        environment:
            PHP_INI_DIR: /usr/local/etc/php/conf.d
        container_name: php7

    php5:
        image: php:5.6-fpm
        expose:
        - 9000
        volumes:
        - '../src:/code'
        - './php/php.ini:/usr/local/etc/php/conf.d/php_extra.ini'
        environment:
            PHP_INI_DIR: /usr/local/etc/php/conf.d
        container_name: php5

# Do not forget to 'docker network create nginx-proxy' before launch,

networks:
  default:
    external:
      name: nginx-proxy